server:
  port: 9090

spring:
  application:
    name: apigate-service
  cloud:
    gateway:
      routes:
        - id: front-endService
          uri : http://localhost:8080
          predicates:
            - Path=/board/**

        - id: back-emdService
          uri : http://localhost:8081
          predicates:
            - Path=/boord/**

